= Integrated Pipelines for Hybrid Clouds

This document provides details on how to build integrated pipelines for Hybrid clouds using Cloudbee's Jenkins, Artifactory
and Pivotal Cloud Foundry with and emphasis on software delivery. 

We will explore two use cases which are very common when releasing software, 

. Continuous Deployment of a software release to different locations using Cloud Foundry.
. Software promotion using link:http://martinfowler.com/bliki/BlueGreenDeployment.html[Blue/Green] deployments with Cloud Foundry.

== Getting Started

This repo contains the instructions for creating your own Jenkins Jobs to perform the use cases outlined above. 
It also contains a script called link:scripts/delivery.sh[deployment] and link:scripts/promotion.sh[promotion] which 
can be used independently of Jenkins to create your own scripts to cut-n-paste into Jenkins. These scripts test the 
different CF CLI commands outside of Jenkins to make testing easier.

Our example application is link:https://github.com/omearaj/PCF-demo[PCF Map] which is a Spring application designed
to demonstrate Cloud Foundry features. The application demonstrates the following Cloud Foundry features,

. Binding to a Cloud Foundry managed service, Rabbit in this case.
. Spring Auto-Reconfiguration, inject service credentials during deployment, etc.
. Application Health Management, the Kill button will exist the application and cause Cloud Foundry to create a new instance.
. FINISH FEATURES

link:deployment.adoc[Continous Deployment] +
link:promotion.adoc[Software Promotion] +
